# Site settings
title:            Voxel Documentation
email:            robjclucas@gmail.com
description:      Documentation for Voxel.
baseurl:          ""                            # Site subdir  e.g. /blog
url:              "https://voxelated.github.io" # Site maindir
twitter_username:
github_username:

# Build settings
markdown:         kramdown
highlighter:      rouge
include:          ['_pages']
gems:
                  - jekyll-feed
exclude:          ['vendor']
exclude:
                  - Gemfile
                  - Gemfile.lock
                  - scripts
