# Site settings
title:            Pixel Internal Documentation
email:            robjclucas@gmail.com
description:      Internal documentation for all Pixel code and guidelines.
baseurl:          ""    # Site subdir  e.g. /blog
url:              "127.0.0.1" # Site maindir
twitter_username:
github_username:

# Build settings
markdown:         kramdown
highlighter:      rouge
include:          ['_pages']
gems:
                  - jekyll-feed
exclude:
                  - Gemfile
                  - Gemfile.lock
                  - scripts
